TUNING.MOD_LAVAARENA = {
	TAGS = {"smallcreature", "monster", "hostile", "animal", "pig", "largecreature", "tentacle_pillar", "walrus"},
	NOTTAGS = {"follower", "playerghost"},
	SPEAR_GUNGNIR = {
		USES    = {
			TOTAL   = GetModConfigData("SPEAR_GUNGNIR_DURABILITY"),
			NORMAL  = GetModConfigData("SPEAR_GUNGNIR_DURABILITY"),
			SPECIAL = GetModConfigData("SPEAR_GUNGNIR_USES_SECIAL")
		},
		DAMAGES = GetModConfigData("SPEAR_GUNGNIR_DAMAGES"),
		RECHARGETIME = GetModConfigData("SPEAR_GUNGNIR_RECHARGETIME")
	},
	BOOK_ELEMENTAL = {
		USES    = {
			TOTAL   = GetModConfigData("BOOK_ELEMENTAL_DURABILITY"),
			SPECIAL = GetModConfigData("BOOK_ELEMENTAL_USES_SECIAL")
		},
		RECHARGETIME  = GetModConfigData("BOOK_ELEMENTAL_RECHARGETIME"),
		SPELLDURATION = GetModConfigData("BOOK_ELEMENTAL_SPELLDURATION")
	},
	FIREBALLSTAFF = {
		USES    = {
			TOTAL   = GetModConfigData("INFERNALSTAFF_DURABILITY"),
			NORMAL  = GetModConfigData("INFERNALSTAFF_USES_NORMAL"),
			SPECIAL = GetModConfigData("INFERNALSTAFF_USES_SECIAL")
		},
		DAMAGES = {
			NORMAL  = GetModConfigData("INFERNALSTAFF_DAMAGES_NORMAL"),
			SPECIAL = {
				MIN = GetModConfigData("INFERNALSTAFF_DAMAGES_SPECIAL") * 100,
				MAX = GetModConfigData("INFERNALSTAFF_DAMAGES_SPECIAL") * 100 + 100
			}
		},
		RECHARGETIME = GetModConfigData("INFERNALSTAFF_RECHARGETIME")
	},
	HEALINGSTAFF = {
		USES    = {
			TOTAL   = GetModConfigData("HEALINGSTAFF_DURABILITY"),
			NORMAL  = GetModConfigData("HEALINGSTAFF_USES_NORMAL"),
			SPECIAL = GetModConfigData("HEALINGSTAFF_USES_SECIAL")
		},
		DAMAGES       = GetModConfigData("HEALINGSTAFF_DAMAGES"),
		SPELLDURATION = GetModConfigData("HEALINGSTAFF_SPELLDURATION"),
		SLEEPTIME     = GetModConfigData("HEALINGSTAFF_SLEEPTIME"),
		REGENVALUE    = GetModConfigData("HEALINGSTAFF_REGENVALUE"),
		RECHARGETIME  = GetModConfigData("HEALINGSTAFF_RECHARGETIME")
	},
}

TUNING.MOD_LAVAARENA.LAVAARENA_LUCY = {}
TUNING.MOD_LAVAARENA.LAVAARENA_LUCY.BASECD = 3
TUNING.MOD_LAVAARENA.LAVAARENA_LUCY.RANGE = math.huge
TUNING.MOD_LAVAARENA.LAVAARENA_LUCY.DECAYPERCAST = 10
TUNING.MOD_LAVAARENA.LAVAARENA_LUCY.THROWDAMAGE = 65

--turtle----------------------
------------------------------
TUNING.LAVAARENA_TURTILLUS = {}
TUNING.LAVAARENA_TURTILLUS.HEALTH = 1200
TUNING.LAVAARENA_TURTILLUS.KEEPDIST = 30
TUNING.LAVAARENA_TURTILLUS.WALKSPEED = 3
TUNING.LAVAARENA_TURTILLUS.TARGET_DIST = 25
--melee
TUNING.LAVAARENA_TURTILLUS.DAMAGE = 45
TUNING.LAVAARENA_TURTILLUS.RANGE = 4
TUNING.LAVAARENA_TURTILLUS.ATTACK_PERIOD = 1.7
--slides
TUNING.LAVAARENA_TURTILLUS.SLIDEDAMAGE = 45
TUNING.LAVAARENA_TURTILLUS.SLIDE_RADIUS = 3
TUNING.LAVAARENA_TURTILLUS.SLIDES_ALLOWED = 5
--hider
TUNING.LAVAARENA_TURTILLUS.SHELL_REQ_DAMAGE = 350
TUNING.LAVAARENA_TURTILLUS.INSHELL_TIME = 5
TUNING.LAVAARENA_TURTILLUS.SHIELDED_DAMAGE_REDUCTION = 0.95

--scorpion------------------------
----------------------------------
TUNING.LAVAARENA_PEGHOOK = {}
TUNING.LAVAARENA_PEGHOOK.HEALTH = 2550
TUNING.LAVAARENA_PEGHOOK.RUNSPEED = 3
TUNING.LAVAARENA_PEGHOOK.TARGET_DIST = 25
TUNING.LAVAARENA_PEGHOOK.KEEPDIST = 30
--melee
TUNING.LAVAARENA_PEGHOOK.DAMAGE = 50
TUNING.LAVAARENA_PEGHOOK.RANGE = 4
TUNING.LAVAARENA_PEGHOOK.ATTACK_PERIOD = 1.5
--range
TUNING.LAVAARENA_PEGHOOK.RANGE_ATTACK_PERIOD = 10
TUNING.LAVAARENA_PEGHOOK.SPITRANGE = 20
TUNING.LAVAARENA_PEGHOOK.SPITDAMAGE = 5
--splash
TUNING.LAVAARENA_PEGHOOK.STICKY_SPIT = true
TUNING.LAVAARENA_PEGHOOK.SPLASHRADIUS = 3
TUNING.LAVAARENA_PEGHOOK.SPLASHDAMAGE = 70
--spread
TUNING.LAVAARENA_PEGHOOK.SPREAD_TARGETS = 3

--piggy---------------------------
----------------------------------
TUNING.LAVAARENA_BOARON = {}
TUNING.LAVAARENA_BOARON.HEALTH = 350
TUNING.LAVAARENA_BOARON.RUNSPEED = 10
TUNING.LAVAARENA_BOARON.TARGET_DIST = 25
TUNING.LAVAARENA_BOARON.KEEPDIST = 30
TUNING.LAVAARENA_BOARON.SHARE_DIST = 25
--melee
TUNING.LAVAARENA_BOARON.DAMAGE = 20
TUNING.LAVAARENA_BOARON.RANGE = 2
TUNING.LAVAARENA_BOARON.ATTACK_PERIOD = 1.5
--charge
TUNING.LAVAARENA_BOARON.CHARGE_RECHARGE = 5
TUNING.LAVAARENA_BOARON.DAMAGE = 45

--_________lizardmen-------------------------
------------------------------------
TUNING.LAVAARENA_SNAPPER = {}
TUNING.LAVAARENA_SNAPPER.TARGET_DIST = 12
TUNING.LAVAARENA_SNAPPER.KEEP_TARGET_DIST = 20
TUNING.LAVAARENA_SNAPPER.DAMAGE = 25
TUNING.LAVAARENA_SNAPPER.ATTACK_PERIOD = 2.5
TUNING.LAVAARENA_SNAPPER.SPEED = 6
TUNING.LAVAARENA_SNAPPER.HEALTH = 680
TUNING.LAVAARENA_SNAPPER.SHARE_TARGET_DIST = 20
TUNING.LAVAARENA_SNAPPER.ATTACK_RANGE = 4
TUNING.LAVAARENA_SNAPPER.DIST_ATTACK_RANGE = 16
TUNING.LAVAARENA_SNAPPER.TORNS_DAMAGE = 5
TUNING.LAVAARENA_SNAPPER.BANNER_RECHARGE = 15

--_______boarilla--------------------------
------------------------------------
TUNING.LAVAARENA_TRAILS = {}
TUNING.LAVAARENA_TRAILS.SPEED = 7.5
TUNING.LAVAARENA_TRAILS.HEALTH = 7750
TUNING.LAVAARENA_TRAILS.TARGET_DIST = 12
TUNING.LAVAARENA_TRAILS.KEEP_TARGET_DIST = 20
--combat
TUNING.LAVAARENA_TRAILS.DAMAGE = 100
TUNING.LAVAARENA_TRAILS.ATTACK_PERIOD = 2.5
TUNING.LAVAARENA_TRAILS.ATTACK_RANGE = 4
--shield
TUNING.LAVAARENA_TRAILS.SHELL_REQ_DAMAGE = 350
TUNING.LAVAARENA_TRAILS.INSHELL_TIME = 5
TUNING.LAVAARENA_TRAILS.SHIELDED_DAMAGE_REDUCTION = 0.95
--slam
TUNING.LAVAARENA_TRAILS.SLAM_RECHARGE = 5
TUNING.LAVAARENA_TRAILS.SLAM_RADIUS = 5
TUNING.LAVAARENA_TRAILS.SLAM_DAMAGE = 150


--BOARRIOR
local bmod = GetModConfigData("boarrior_damage_mod")

TUNING.LAVAARENA_BOARRIOR = {}
TUNING.LAVAARENA_BOARRIOR.ATTACK_PERIOD = 1.5
TUNING.LAVAARENA_BOARRIOR.ATTACK_RANGE = 7
TUNING.LAVAARENA_BOARRIOR.SPEED = 14
TUNING.LAVAARENA_BOARRIOR.HEALTH = GetModConfigData("boarrior_health")
TUNING.LAVAARENA_BOARRIOR.BONUSHEALTH = GetModConfigData("boarrior_bonus_health")

TUNING.LAVAARENA_BOARRIOR.WHIRLWINDDAMAGE = 60 * bmod
TUNING.LAVAARENA_BOARRIOR.GROUNDSLAMDAMAGE = 30 * bmod
TUNING.LAVAARENA_BOARRIOR.GROUNDFIRADAMAGE = 80 * bmod
TUNING.LAVAARENA_BOARRIOR.COMBOLASTHITDAMAGE = 25 * bmod
TUNING.LAVAARENA_BOARRIOR.COMBOLASTHITDAMAGE_FATAL = 200
TUNING.LAVAARENA_BOARRIOR.METEORDAMAGE = 80 * bmod
TUNING.LAVAARENA_BOARRIOR.HANDDAMAGE = 250 * bmod

TUNING.LAVAARENA_BOARRIOR.WHIRLWINDRADIUS = 5
TUNING.LAVAARENA_BOARRIOR.WHIRLWINDNEEDTARGETS = 2

TUNING.LAVAARENA_BOARRIOR.WHIRLWINDCD = 12
TUNING.LAVAARENA_BOARRIOR.METEORCD = 12
TUNING.LAVAARENA_BOARRIOR.GROUNDBURNCD = 12
TUNING.LAVAARENA_BOARRIOR.GROUNDSLAMCD_1 = 20
TUNING.LAVAARENA_BOARRIOR.GROUNDSLAMCD_2 = 12
TUNING.LAVAARENA_BOARRIOR.GROUNDSLAMCD_3 = 8
TUNING.LAVAARENA_BOARRIOR.GROUNDSLAMCD_4 = 2
TUNING.LAVAARENA_BOARRIOR.COMBOCD = 20
